blank_issues_enabled: true
contact_links:
  - name: â“ Question
    url: https://github.com/inducer/pudb/discussions/categories/q-a
    about: Ask and answer questions about pudb on Discussions
  - name: ğŸ”§ Troubleshooting
    url: https://github.com/inducer/pudb/discussions/categories/troubleshooting
    about: For troubleshooting help, see the Discussions
